version: '2'
services:
  get:
    image: golang:1.10
    container_name: go_get
    volumes:
      - .:/go
    command: ["go", "get", "-d", "./..."]
  build:
    image: golang:1.10
    container_name: go_build
    volumes:
      - .:/go
    depends_on: 
      - get
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    command: ["go", "build", "-a", "-ldflags", "-extldflags \"-static\"", "-o", "app"]
  app:
    image: alpine:3.7
    container_name: go_app
    volumes:
      - .:/go
    depends_on:
      - build
    command: ["/go/app"]
